name: amazncls
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - ipykernel=6.29.5
  - ipython=8.31.0
  - python=3.11.11
  - pip:
      - fastapi==0.115.7
      - fire==0.7.0
      - huggingface-hub==0.27.1
      - mlflow==2.20.0
      - numpy==2.2.2
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - pandas==2.2.3
      - pillow==11.1.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyspark==3.5.4
      - pytest==8.3.4
      - pytest-mock==3.14.0
      - python-dotenv==1.0.1
      - pyyaml==6.0.2
      - scikit-learn==1.6.1
      - scipy==1.15.1
      - seaborn==0.13.2
      - streamlit==1.41.1
      - termcolor==2.5.0
      - tokenizers==0.21.0
      - toml==0.10.2
      - torch==2.5.1
      - tqdm==4.67.1
      - transformers==4.48.1
      - typing==3.7.4.3
      - uvicorn==0.34.0
